workflows:
  ios-capacitor:
    name: Build iOS App for Cigar Manor
    environment:
      vars:
        CAPACITOR_PROJECT_DIR: "."
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios
      - name: Add iOS platform
        script: npx cap add ios
      - name: Copy Web Assets
        script: npx cap copy ios
      - name: Build iOS project
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/App.xcarchive
    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/**/*.dSYM
